/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jrestaurant.gui.cashier;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class MainCashier extends javax.swing.JFrame {
        // private MainFrame frame;
    
    /**
     * Creates new form MainCashier
     */
    public MainCashier() {
         setTitle("CashierPage"); 
         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         setSize(1000,800);
         setLayout(null);
         setLocationRelativeTo(null);
         
         
         
        JLabel Name = new JLabel("JRestaurant");
        Name.setFont(new Font("Arial", Font.BOLD, 30));
         Name.setBounds((int)(getWidth()*0.21),(int)(getHeight()*0.13),(int)(getWidth()*0.5) , (int)(getHeight()*0.2));
         add(Name);
         
//        JLabel action = new JLabel("common Action");
//        action.setFont(new Font("Arial" , Font.BOLD,20));
//        action.setBounds((int)(getWidth()*0.21),(int)(getHeight()*0.6),(int)(getWidth()*0.5) , (int)(getHeight()*0.2));
//        add(action);
         
        JButton MakeOrderButton2 = new JButton("Make Order");
          MakeOrderButton2.setFont(new Font("Arial", Font.BOLD, 18));
          MakeOrderButton2.setBackground(Color.DARK_GRAY);
          MakeOrderButton2.setForeground(Color.white);
          MakeOrderButton2.setBounds((int)(getWidth()*0.21),(int)(getHeight()*0.6),(int)(getWidth()*0.20) - 30 , 40);
          add(MakeOrderButton2);
        
        MakeOrderButton2.addActionListener(e -> {
              //new MakeOrderPage(); 
                });
        
        
        
        JPanel LeftPanel = new JPanel();
            LeftPanel.setBounds(0, 0,(int)(getWidth()*0.20), getHeight());
            LeftPanel.setBackground(new Color(25, 25, 25));
            LeftPanel.setLayout(null);
            add(LeftPanel);
            
            
        JButton MakeOrderButton = new JButton("Make Order");
          MakeOrderButton.setFont(new Font("Arial", Font.BOLD, 18));
          MakeOrderButton.setBackground(Color.DARK_GRAY);
          MakeOrderButton.setForeground(Color.BLACK);
          MakeOrderButton.setBounds(20, (int)(getHeight()*0.30), (int)(getWidth()*0.20) - 30, 35);
          LeftPanel.add(MakeOrderButton);
          
          
        JButton reservationButton = new JButton("Reservation");
          reservationButton.setFont(new Font("Arial", Font.BOLD, 18));
          reservationButton.setBackground(Color.DARK_GRAY);
          reservationButton.setForeground(Color.BLACK);
          reservationButton.setBounds(20, (int)(getHeight()*0.38), (int)(getWidth()*0.20) - 30, 35);
          LeftPanel.add(reservationButton);
          
          
          
          JButton OrdersButton = new JButton("Orders");
          OrdersButton.setFont(new Font("Arial", Font.BOLD, 18));
          OrdersButton.setBackground(Color.DARK_GRAY);
          OrdersButton.setForeground(Color.BLACK);
          OrdersButton.setBounds(20, (int)(getHeight()*0.46), (int)(getWidth()*0.20) - 30, 35);
          LeftPanel.add(OrdersButton);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
